name: apphids
description: "A cross-platform app for aphid detection and chemigation tracking."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Core packages
  flutter_riverpod: ^2.4.9        # State management
  go_router: ^11.1.0              # Navigation
  responsive_framework: ^0.2.0    # Responsive UI

  # Platform-specific (conditional imports)
  shared_preferences: ^2.2.2      # Mobile storage
  shared_preferences_web: ^2.1.1  # Web storage
  url_launcher: ^6.1.11           # Cross-platform links

  # UI/UX
  fl_chart: ^0.65.0               # Charts
  intl: ^0.18.1                   # Date formatting
  flutter_native_splash: ^2.4.6

  syncfusion_flutter_gauges: ^23.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0           # Linting
  build_runner: ^2.4.6            # Code generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/icons/app_icon.png


flutter_native_splash:
  color: "#333333"  # background color (matches your image background)
  image: assets/images/splash.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
